<a href="https://colab.research.google.com/github/Muhammed1978/Amazon-Product-Review-Analysis/blob/main/DataAnalysis0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Analysis with Python

***Numpy and Pandas

***How to import Python Package

n

In [ ]:
#Example 1
import numpy as np
import panda as pd

In [ ]:
#Example 2
#For the constant (pi) which is rounded to 3.142
numpypi = np.pi
print(numpypi)

3.141592653589793


In [ ]:
#Example 3
# For the square root of 16(square root of 16)

np.sqrt(16)

np.float64(4.0)

In [ ]:
np.sqrt(15)

np.float64(3.872983346207417)

#Importing packages with alias

It is common for python users to import pacakages with alias.

Alias helps us to shorten the name of the packages while rferencing a certian function with it.

The syntax looks this:


In [ ]:
#Example 1
import module_name as another_name
import numpy as np

***We can now refer to the function as *np.function_name *rather *numpy.function_name*

In [ ]:
#Example 2 :For the constant(pi) which is rounded to 3.142
numpypi = np.pi
print(numpypi)

3.141592653589793


In [ ]:
#Example 3:For the square root of 16 ()
np.sqrt(16)


np.float64(4.0)

#Loading functions from a pacakge

To load selected functions from a module,we use the following syntax:


In [ ]:
from module_name import funcname

In [ ]:
#Example 4:import only sqrt,pi,floor from numpy module
from numpy import sqrt,pi, floor


***You can use those functions without referencing numpy again.

In [ ]:
#Example 4
np.sqrt(64)

np.float64(8.0)

In [ ]:
#example 5
numpypi = np. pi
print(numpypi)

3.141592653589793


In [ ]:
#Example 5:np.floor;only returns the integer part
np.floor(3.141592653)

np.float64(3.0)

#Data science modules

For some other modules,it is common to use aliases, for example condider the following adata science packages:

. Pandas

 Pandas for data manipulation n-dimesnional arrays.

. Matplotlib.pyplot

  Matplotlib and Seaborn for data visualization

. Seaborn

 Its for data visualization

. Scikit-learn

Its for building machine learning models.

***Short exercise***

Try to import the follwoing modules:

. Numpy

. Pandas

. Seaborn

. Matplotlib


In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


#NUMPY

**1. Introduction**

Numpy(Numerical Python) is the foundational library for computing in python ,pandas,scikit-learn,statsmodel and many other libraries were built on top of Numpy arrays.

In ths module,learners will:

 .  Understand what a Numpy array is and why it is  preferedd to python lists in data science .

 .  Create and manipulate arrays of different shapes and data types.

 .  Perform vectorised operations,aggregations, and boolean filtering.

 .  Reshape and combine arrays in ways that prepare data for pandas.

 . work through realistic 'mini data scince' examples using Numpy.


**2. Prerequistes**

Before you start,you should be comfortable with:

. Basic Python syntax (variables ,lists,loops,functionas)
. Running cells in Jupyter noteboo or similar environment.


**3. Getting started**

 import numpy as np

 np_version_

 You should see a version number such as 1.26.4.Any recent version is fine.








# Python List vs Numpy Arrays

We start with a familiar structure the Python List

Then we compare it with Numpy arrays and see why Numpy is the preferred is the preferred choice in data science.


***Python list

.  A python list can hold different types,is flexible but arithmentix is ot vectorised.

.  For  example  trying heights_list*2  repeats the list instead of doubling values.

In [ ]:
heights_list = [160, 165, 170, 172, 168]
type(heights_list)

list

***You can reapeat the arrays of number in a list using (*) operator.

In [ ]:
#Example
heights_list * 2

[160, 165, 170, 172, 168, 160, 165, 170, 172, 168]

**You can add a number to the arrays in the list using (+) operator.

In [ ]:
#Example
import numpy as np
heights_array = np.array(heights_list)
heights_array + 1

array([161, 166, 171, 173, 169])

#Creating Numpy array


In [ ]:
#Example
heights =np.array([160, 615, 170, 172, 168])
type(heights)

***You can repeat the array by using multiplication operator.

In [ ]:
heights_array * 2

array([320, 330, 340, 344, 336])

***You can also add a value to the array by using (+) operator.

In [ ]:
heights_array + 1

array([161, 166, 171, 173, 169])

****The operation above is essential for data science,because it allows us to work with columns of data effeciently,just like in pandas.

# Exercise 1: List vs Arrays

1. Create a python list called weights_list with five weights(in kilograms).

2. Convert it to Numpy array called weights_array.

3. Multiply the list by 3 and the array by 3

4. Compare the results and explain the difference in one or two sentences in a markdown cell.



In [ ]:
#Solution: Creating python list
weight_list = [50,60,70,80,90]
type(weight_list)


list

In [ ]:
#Solution: Converting list to numpy array.
weight_array = np.array(weight_list)
type(weight_array)

numpy.ndarray

In [ ]:
#Solution:Multiplying list by 3, and array by 3.
weight_list * 3

[50, 60, 70, 80, 90, 50, 60, 70, 80, 90, 50, 60, 70, 80, 90]

In [ ]:
#Solution:Mutltiplying array by 3
weight_array * 3

array([150, 180, 210, 240, 270])

***Getting Square Root of array***


In [ ]:
#Example
np.sqrt(weight_list)


array([7.07106781, 7.74596669, 8.36660027, 8.94427191, 9.48683298])

# Creating NumPy Arrays

NumPy arrays are the primary structure we will use throughout this module.They come in two forms *vectors  and **matrices.Vectors are strictly one-dimensional arrays, and matrices are two-dimesional arrays (though a matrix may have only one rwo or one column).

NumPy provides several ways to create arrays:

. From Pyhton lists

. From helper fucntions like  a **range **and **linespace**.

. From construction that create zeros,ones or identity matrices .

.  From random number generation (useful simulations).



**From Python list**

In [4]:
#Example 1
weights = np.array([60.5, 65.0, 70.2, 68.3, 66.8])
weights

array([60.5, 65. , 70.2, 68.3, 66.8])

In [2]:
import numpy as np
#Example 2: Height in meters
heights = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
heights

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [5]:
#Example 3: Calculation of BMI(Body Mass Index)
import numpy as np
bmi = weights/heights**2
bmi

array([20.21450767, 23.03004535, 24.00738689, 19.12040536, 20.84828813])

***According to the World Health Organization (WHO) and other health organizations, the standard BMI categories for adults are:

| BMI (kg/m²)    | Category          |
| :------------- | :---------------- |
| Below 18.5     | Underweight       |
| 18.5 – 24.9    | Normal weight     |
| 25.0 – 29.9    | Overweight        |
| 30.0 and Above | Obese             |

# Derive variables

***Exercise:

Create two variables and third variable as the derived

In [12]:
#Solution: Calculation of efficiency of HP compressor
import numpy as np
suction_pressures =np.array([185.10, 186.1, 186.6, 187.1, 188.2, 189.0, 190.2,195.1, 199.10, 200.00])
discharge_pressures =np.array([301.0,315.5, 320.1, 325.1, 328.0, 331.5, 335.6, 337.21, 339.11, 340.0 ])
suction_pressures
discharge_pressures



array([301.  , 315.5 , 320.1 , 325.1 , 328.  , 331.5 , 335.6 , 337.21,
       339.11, 340.  ])

In [14]:
cpmpressor_efficiency = discharge_pressures/suction_pressures
cpmpressor_efficiency

array([1.62614803, 1.69532509, 1.71543408, 1.73757349, 1.74282678,
       1.75396825, 1.76445846, 1.72839569, 1.70321447, 1.7       ])

# Using helper function arange

arange() is similar to the built-in range() function,but it returns a NumPy array instead of a list. It is use to generate evenly spaced values within a speficied interval.

In [15]:
#Example 1
a = np.arange(10) # 0 to 9
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#Example 2
np.arange(1, 8) # Start, stop


array([1, 2, 3, 4, 5, 6, 7])

In [17]:
#Example 3
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
#Example 4
np.arange(1, 10, 2) # Start, stop, step

array([1, 3, 5, 7, 9])

# Using helper function like linespace

It returns evenly spaced numbers over a specified interval

In [4]:
import numpy as np
np.linspace(0, 10) # start, stop, num = 50(default)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [21]:
# Example 2
np.linspace(0, 10, 3) # start, stop, (number of samples)

array([ 0.,  5., 10.])

# From Random Numbers Generators(useful for simulations for data science experiments)

NumPy's random module provides functions to generate random numbers and arrays.Functions like randint, rand,randn are useful functions to generate random numbers for simulations and experiments in data science.

#rand

Generate random numbers from a uniform distribution over [0,1].

In [3]:
import numpy as np
#Example 1
np.random.rand(4)

array([0.09274492, 0.31716894, 0.5275168 , 0.31737908])

In [6]:
#Example 2
np.random.rand(50)

array([0.61082317, 0.1367447 , 0.30570971, 0.10586519, 0.82771363,
       0.67410184, 0.34195942, 0.12454688, 0.06652106, 0.14248794,
       0.33932127, 0.55310374, 0.02515045, 0.08830471, 0.0594832 ,
       0.31623381, 0.94872115, 0.55310591, 0.77491264, 0.32861983,
       0.70065368, 0.80954538, 0.45911277, 0.80353366, 0.94369332,
       0.88371397, 0.10113483, 0.01576192, 0.53165027, 0.1333047 ,
       0.80379254, 0.99026981, 0.07973433, 0.4552093 , 0.52871067,
       0.27540997, 0.85317383, 0.59863243, 0.30055009, 0.84942294,
       0.11120872, 0.01883707, 0.40973996, 0.53301431, 0.72316217,
       0.23963229, 0.38999983, 0.68794714, 0.45580808, 0.35237038])

# randint

Generate random integers from low (inclusive) to high(exlusive)

In [5]:
# Example 1
np.random.randint(1, 6, size = 12 ) # random integers between 1 and 5 (6 excluded)


array([3, 3, 4, 5, 1, 5, 1, 1, 3, 2, 4, 1])

In [10]:
# Example 2:Find seed for reproducibility
np.random.seed(42)

np.random.randint(1, 6, size = 12 ) # random integers between 1 and 5 (6 excluded)

array([4, 5, 3, 5, 5, 2, 3, 3, 3, 5, 4, 3])

# randn

Generate random numbers from a standard normal distribution (mean = 0, standard deviation =1)

In [13]:
# Example 1
import numpy as np
np.random.rand(5)

array([0.06505159, 0.94888554, 0.96563203, 0.80839735, 0.30461377])

In [14]:
# Example 2
np.random.randn(5,5)

array([[ 0.291034  , -0.63555974, -1.02155219, -0.16175539, -0.5336488 ],
       [-0.00552786, -0.22945045,  0.38934891, -1.26511911,  1.09199226],
       [ 2.77831304,  1.19363972,  0.21863832,  0.88176104, -1.00908534],
       [-1.58329421,  0.77370042, -0.53814166, -1.3466781 , -0.88059127],
       [-1.1305523 ,  0.13442888,  0.58212279,  0.88774846,  0.89433233]])

In [2]:
import numpy as np
#Example 3
np.random.randn(20) # standard normal distribution

array([-0.8886729 , -0.74429894,  1.09617846,  0.28435498,  1.49691008,
        2.28903225, -2.35651285,  0.30742045,  0.29575832, -1.54236112,
        1.15123637, -0.37251597, -0.02202039,  0.08457294,  1.0045766 ,
       -0.68733298,  0.14744307, -0.77603558, -1.27807674,  0.56697401])

In [3]:
# Example 4
np.random.randn(20).mean()

np.float64(0.1756696276655512)

# Exercise : Simulate number for the scores of 100 students in an exam (50-90).

In [18]:
#Solution: Simulating  number for the scores of 100 students in an exam(5-90)
import numpy as np
np.random.seed(20251210)

np.random.randint(50, 90, size = 100)

array([88, 70, 60, 54, 80, 80, 83, 51, 79, 88, 88, 64, 69, 60, 86, 72, 64,
       54, 76, 59, 66, 53, 72, 54, 68, 63, 71, 63, 58, 65, 75, 83, 82, 72,
       79, 78, 55, 50, 71, 88, 79, 85, 60, 82, 87, 77, 85, 76, 83, 71, 55,
       86, 66, 54, 78, 87, 61, 52, 50, 61, 78, 74, 55, 70, 61, 75, 77, 66,
       61, 75, 79, 52, 73, 58, 79, 88, 76, 65, 78, 53, 61, 88, 82, 81, 52,
       54, 54, 53, 57, 62, 69, 50, 54, 89, 63, 70, 79, 57, 74, 66])