<a href="https://colab.research.google.com/github/Muhammed1978/Amazon-Product-Review-Analysis/blob/main/DataAnalysis0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Analysis with Python

***Numpy and Pandas

***How to import Python Package

n

In [ ]:
#Example 1
import numpy as np
import panda as pd

In [ ]:
#Example 2
#For the constant (pi) which is rounded to 3.142
numpypi = np.pi
print(numpypi)

3.141592653589793


In [ ]:
#Example 3
# For the square root of 16(square root of 16)

np.sqrt(16)

np.float64(4.0)

In [ ]:
np.sqrt(15)

np.float64(3.872983346207417)

#Importing packages with alias

It is common for python users to import pacakages with alias.

Alias helps us to shorten the name of the packages while rferencing a certian function with it.

The syntax looks this:


In [ ]:
#Example 1
import module_name as another_name
import numpy as np

***We can now refer to the function as *np.function_name *rather *numpy.function_name*

In [ ]:
#Example 2 :For the constant(pi) which is rounded to 3.142
numpypi = np.pi
print(numpypi)

3.141592653589793


In [ ]:
#Example 3:For the square root of 16 ()
np.sqrt(16)


np.float64(4.0)

#Loading functions from a pacakge

To load selected functions from a module,we use the following syntax:


In [ ]:
from module_name import funcname

In [ ]:
#Example 4:import only sqrt,pi,floor from numpy module
from numpy import sqrt,pi, floor


***You can use those functions without referencing numpy again.

In [ ]:
#Example 4
np.sqrt(64)

np.float64(8.0)

In [ ]:
#example 5
numpypi = np. pi
print(numpypi)

3.141592653589793


In [ ]:
#Example 5:np.floor;only returns the integer part
np.floor(3.141592653)

np.float64(3.0)

#Data science modules

For some other modules,it is common to use aliases, for example condider the following adata science packages:

. Pandas

 Pandas for data manipulation n-dimesnional arrays.

. Matplotlib.pyplot

  Matplotlib and Seaborn for data visualization

. Seaborn

 Its for data visualization

. Scikit-learn

Its for building machine learning models.

***Short exercise***

Try to import the follwoing modules:

. Numpy

. Pandas

. Seaborn

. Matplotlib


In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


#NUMPY

**1. Introduction**

Numpy(Numerical Python) is the foundational library for computing in python ,pandas,scikit-learn,statsmodel and many other libraries were built on top of Numpy arrays.

In ths module,learners will:

 .  Understand what a Numpy array is and why it is  preferedd to python lists in data science .

 .  Create and manipulate arrays of different shapes and data types.

 .  Perform vectorised operations,aggregations, and boolean filtering.

 .  Reshape and combine arrays in ways that prepare data for pandas.

 . work through realistic 'mini data scince' examples using Numpy.


**2. Prerequistes**

Before you start,you should be comfortable with:

. Basic Python syntax (variables ,lists,loops,functionas)
. Running cells in Jupyter noteboo or similar environment.


**3. Getting started**

 import numpy as np

 np_version_

 You should see a version number such as 1.26.4.Any recent version is fine.








# Python List vs Numpy Arrays

We start with a familiar structure the Python List

Then we compare it with Numpy arrays and see why Numpy is the preferred is the preferred choice in data science.


***Python list

.  A python list can hold different types,is flexible but arithmentix is ot vectorised.

.  For  example  trying heights_list*2  repeats the list instead of doubling values.

In [ ]:
heights_list = [160, 165, 170, 172, 168]
type(heights_list)

list

***You can reapeat the arrays of number in a list using (*) operator.

In [ ]:
#Example
heights_list * 2

[160, 165, 170, 172, 168, 160, 165, 170, 172, 168]

**You can add a number to the arrays in the list using (+) operator.

In [ ]:
#Example
import numpy as np
heights_array = np.array(heights_list)
heights_array + 1

array([161, 166, 171, 173, 169])

#Creating Numpy array


In [ ]:
#Example
heights =np.array([160, 615, 170, 172, 168])
type(heights)

***You can repeat the array by using multiplication operator.

In [ ]:
heights_array * 2

array([320, 330, 340, 344, 336])

***You can also add a value to the array by using (+) operator.

In [ ]:
heights_array + 1

array([161, 166, 171, 173, 169])

****The operation above is essential for data science,because it allows us to work with columns of data effeciently,just like in pandas.

# Exercise 1: List vs Arrays

1. Create a python list called weights_list with five weights(in kilograms).

2. Convert it to Numpy array called weights_array.

3. Multiply the list by 3 and the array by 3

4. Compare the results and explain the difference in one or two sentences in a markdown cell.



In [ ]:
#Solution: Creating python list
weight_list = [50,60,70,80,90]
type(weight_list)


list

In [ ]:
#Solution: Converting list to numpy array.
weight_array = np.array(weight_list)
type(weight_array)

numpy.ndarray

In [ ]:
#Solution:Multiplying list by 3, and array by 3.
weight_list * 3

[50, 60, 70, 80, 90, 50, 60, 70, 80, 90, 50, 60, 70, 80, 90]

In [ ]:
#Solution:Mutltiplying array by 3
weight_array * 3

array([150, 180, 210, 240, 270])

***Getting Square Root of array***


In [ ]:
#Example
np.sqrt(weight_list)


array([7.07106781, 7.74596669, 8.36660027, 8.94427191, 9.48683298])

# Creating NumPy Arrays

NumPy arrays are the primary structure we will use throughout this module.They come in two forms *vectors  and **matrices.Vectors are strictly one-dimensional arrays, and matrices are two-dimesional arrays (though a matrix may have only one rwo or one column).

NumPy provides several ways to create arrays:

. From Pyhton lists

. From helper fucntions like  a **range **and **linespace**.

. From construction that create zeros,ones or identity matrices .

.  From random number generation (useful simulations).



**From Python list**

In [4]:
#Example 1
weights = np.array([60.5, 65.0, 70.2, 68.3, 66.8])
weights

array([60.5, 65. , 70.2, 68.3, 66.8])

In [2]:
import numpy as np
#Example 2: Height in meters
heights = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
heights

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [5]:
#Example 3: Calculation of BMI(Body Mass Index)
import numpy as np
bmi = weights/heights**2
bmi

array([20.21450767, 23.03004535, 24.00738689, 19.12040536, 20.84828813])

***According to the World Health Organization (WHO) and other health organizations, the standard BMI categories for adults are:

| BMI (kg/m²)    | Category          |
| :------------- | :---------------- |
| Below 18.5     | Underweight       |
| 18.5 – 24.9    | Normal weight     |
| 25.0 – 29.9    | Overweight        |
| 30.0 and Above | Obese             |

# Derive variables

***Exercise:

Create two variables and third variable as the derived

In [12]:
#Solution: Calculation of efficiency of HP compressor
import numpy as np
suction_pressures =np.array([185.10, 186.1, 186.6, 187.1, 188.2, 189.0, 190.2,195.1, 199.10, 200.00])
discharge_pressures =np.array([301.0,315.5, 320.1, 325.1, 328.0, 331.5, 335.6, 337.21, 339.11, 340.0 ])
suction_pressures
discharge_pressures



array([301.  , 315.5 , 320.1 , 325.1 , 328.  , 331.5 , 335.6 , 337.21,
       339.11, 340.  ])

In [13]:
cpmpressor_efficiency = suction_pressures/discharge_pressures
cpmpressor_efficiency

array([0.61495017, 0.58985737, 0.58294283, 0.57551523, 0.57378049,
       0.57013575, 0.56674613, 0.57857122, 0.58712512, 0.58823529])

# Using helper function arange

arange() is similar to the built-in range() function,but it returns a NumPy array instead of a list. It is use to generate evenly spaced values within a speficied interval.