<a href="https://colab.research.google.com/github/Muhammed1978/Amazon-Product-Review-Analysis/blob/main/Yet_another_copy_of_DataAnalysis_Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pre - requisites**


 (1) Basic Python Syntax

   - *variables*

  - *Lists*
  
  - *Loops*
  
  - *Functions*

  (2) Running cells in a jupyter notebook or similar environment.

  


# **Data Analysis with Python**

***Numpy and Pandas ***

***How to import Python Package**

 1. Import numpy as np

 2. np_version_

 **Note**

 *You will see a version number such as 1.26.4 in anaconda*.

(a) *Numpy and Pandas*

In [ ]:
# Example 1
import numpy as np
import pandas as pd


In [ ]:
# Example 2 : Find constant (pi) rounded to 3.142

import numpy as np
import pandas as pd

np.version

<module 'numpy.version' from '/usr/local/lib/python3.12/dist-packages/numpy/version.py'>

In [ ]:
numpypi = np.pi
print(numpypi)

3.141592653589793


In [ ]:
# Example 3 :Find the square root of 16

np.sqrt(16)


np.float64(4.0)

In [ ]:
np.sqrt(25)

np.float64(5.0)

In [ ]:
np.sqrt(64)

np.float64(8.0)

(b) *Importing packages with alias*

1. It is common for python users toimport packagaes with alias.

2. Alias helps us to shorten the name of the packages while referencing acertain function with it.The syntax look thus:



In [ ]:
# Example 1
import module_name as another_name
import numpy as np

**We can now refer to the functions as

*np.function_name* rather than *numpy.function_name*

In [ ]:
# Example 2 :For the contant 9(pi) which is rounded to 3.142
import numpy as np
numpypi = np.pi
print(np.pi)

3.141592653589793


(c) *Loading Functions from a package*

To load se;scted functions from a module , we use the following syntax:


In [ ]:
from math import sqrt

# Now you can use sqrt directly without the 'math.' prefix
result = sqrt(81)
print(f"The square root of 81 is {result}")

The square root of 81 is 9.0


In this example:

*   `from math import sqrt` specifically imports only the `sqrt` function from the `math` module.
*   This allows you to call `sqrt()` directly, without having to prefix it with `math.` (e.g., `math.sqrt()`).

This can be useful if you only need a few specific functions from a large module and want to keep your code cleaner.

**You can also use those functions without referencing numpy again.

In [ ]:
# Example 4
np.sqrt(64)

np.float64(8.0)

In [ ]:
# Example 5
numpypi = np.pi
print(numpypi)

3.141592653589793


In [ ]:
# Example 6 : np.floor; only returns the integer part
np.floor(3.142)

np.float64(3.0)

# ** Data-science Modules**
 For some other modules ,it is common to use aliases ,for example, consider the following packages :

 1. Numpy:

    It is use for numerical analysis


2.  Pandas:

    It is  for data manipulation of n-dimensional of arrays.


 3. Matplotlib.pyplot:

    It use for data visualization.

 4. Seaborn:

    It is use for data visualization .

5. Scikit-learn:

    It  is usefor building machine learning models.

**Short Exercises**

Try and import the following modules ⁉

1. Numpy

2. Pandas

3. Matplotlib.py

4. Seaborn



In [ ]:
#  Solution: Importing Numpy;Pandas;Seaborn;matplotlib.pyplot
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


**NUMPY**

A.  **Introduction**

Numpy(Numerical Python) is the foundational library for computing in python ,pandas, scikit-learn ,statsmodel and many other libraries were built on top of Numpy arrays.
 In this modules, learners will:
  1. Understand what a Numpy array is and why it is prefered to python list in data science.

  2. Create and manipulate  arrays of different shapes and data types .

  3. Perform vectorised operations ,aggregations and boolean filtering.

  4. Reshape and combine arrays in ways that prepare data for pandas.

  5. Work through realistic mini datascience examples using Numpy.


B.  **Pre- requisites**

  Before you start , you should be confortable with :
  
  1. Basic Python syntax (variables, lists, loops & functions).

  2. Running cells in Jupyter notebook or similar environment .

C. **Getting started**

1. Inport numpy as np

2. np_version_

3. You should see a ve4sion number such as 1.26.4 or any recent version is fine.

# **Python List vs Numpy Arrays**

We start with a familair structure the python list, then we comapare it with a Numpy arrays and see why Numpy is the prefered choice in data science.

**Python List**

1. Python list can hold diffrent types ,its flexible ,but, arithmetric is not vectorised.

2. For example trying height_lists**2 - will repeat the list instead of doubling.





In [1]:
# Example 1
height_lists = [160, 165, 170, 168]

type(height_lists)

list

* You can also repeat the arrays of numbers in alist using ()  operator.



In [3]:
# Example 2

import numpy as np
height_lists = [160, 165, 170, 172, 168]
type(height_lists)
height_array = np.array(height_lists)
height_array *2


array([320, 330, 340, 344, 336])

In [4]:
height_array*3

array([480, 495, 510, 516, 504])

**You can add a number to the arrays in the list using (+) operator**

In [5]:
# Example 1
import numpy as np
height_array = np.array(height_lists)
height_array + 1


array([161, 166, 171, 173, 169])

**You can repeat the array by using multiplication operator**

In [6]:
height_array * 2

array([320, 330, 340, 344, 336])

**You can also repeat the array by using (+) operator**

In [7]:
# Example
height_array + 1


array([161, 166, 171, 173, 169])